[package]
name = "module-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
colored.workspace = true
convert_case.workspace = true
json.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true
toml.workspace = true
